#!/usr/bin/env python3
"""
One-off migration script: finds every literal hex color across the app's CSS
Modules (Layout.module.css excluded on purpose — its sidebar is a deliberately
always-dark navy regardless of overall theme, the same choice VS Code/Slack
make for their nav rail), replaces each with a CSS custom property, and
generates the light/dark token definitions for src/theme.css.

Light values are always the ORIGINAL literal — this guarantees the existing
light theme is pixel-identical to today; only a `prefers-color-scheme: dark`
media query can differ from it. Dark values are derived by inverting each
color's HSL lightness (compressed toward a comfortable range rather than a
literal 100-L, which reads harsh at the extremes), preserving hue/saturation.
This is mechanical rather than hand-designed per color: with 143 distinct
literals across 22 files and most of them one-off pastel tints, hand-tuning
each was not tractable in one pass. Run once, output is committed as regular
source — this script is not part of the build.
"""
import colorsys
import glob
import os
import re

ROOT = os.path.join(os.path.dirname(__file__), '..', 'src')
FILES = sorted(
    f for f in glob.glob(os.path.join(ROOT, '**', '*.module.css'), recursive=True)
    if not f.endswith('Layout.module.css')
) + [os.path.join(ROOT, 'index.css')]

HEX_RE = re.compile(r'#([0-9a-fA-F]{3}|[0-9a-fA-F]{6})\b')


def expand(h):
    """3-digit -> 6-digit, lowercase."""
    h = h.lower()
    if len(h) == 3:
        h = ''.join(c * 2 for c in h)
    return h


def hex_to_rgb(h):
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))


def rgb_to_hex(rgb):
    return '#{:02x}{:02x}{:02x}'.format(*[max(0, min(255, round(c))) for c in rgb])


def invert_lightness(h):
    r, g, b = [c / 255 for c in hex_to_rgb(h)]
    hue, l, s = colorsys.rgb_to_hls(r, g, b)[0], colorsys.rgb_to_hls(r, g, b)[1], colorsys.rgb_to_hls(r, g, b)[2]
    # Compress toward [0.10, 0.92] rather than a literal 1-L: avoids pure
    # black/white extremes, which read as harsh, dead flat surfaces next to
    # everything else's softer tones.
    new_l = 1 - l
    new_l = 0.10 + new_l * (0.92 - 0.10)
    r2, g2, b2 = colorsys.hls_to_rgb(hue, new_l, s)
    return rgb_to_hex((r2 * 255, g2 * 255, b2 * 255))


# ── Pass 1: collect every distinct color and every literal spelling of it ──
spellings_by_canon = {}   # canon hex6 -> set of literal strings seen ('#FFF', '#ffffff', ...)
file_contents = {}
for path in FILES:
    with open(path) as f:
        text = f.read()
    file_contents[path] = text
    for m in HEX_RE.finditer(text):
        literal = m.group(0)
        canon = expand(m.group(1))
        spellings_by_canon.setdefault(canon, set()).add(literal)

print(f'{len(spellings_by_canon)} distinct colors across {len(FILES)} files')

# ── Pass 2: token names + light/dark values ──
tokens = {}  # canon -> (var_name, light_value, dark_value)
for canon in spellings_by_canon:
    var_name = f'--c-{canon}'
    tokens[canon] = (var_name, f'#{canon}', invert_lightness(canon))

# ── Pass 3: rewrite every file, longest literal first so '#fff' inside
# '#ffffff'-adjacent text never partially matches ──
for path in FILES:
    text = file_contents[path]

    def repl(m):
        canon = expand(m.group(1))
        return f'var({tokens[canon][0]})'

    new_text = HEX_RE.sub(repl, text)
    if new_text != text:
        with open(path, 'w') as f:
            f.write(new_text)

# ── theme.css ──
# No manual light/dark toggle in this app (yet) — this follows the OS setting
# only, via prefers-color-scheme, which is the native-app-like behavior
# (matches how macOS/iOS/Windows apps switch automatically). If a manual
# override is ever added, gate these dark values behind an additional
# :not([data-theme="light"]) / [data-theme="dark"] pair rather than editing
# color-by-color here.
lines = [
    '/*',
    ' * Generated by scripts/gen-dark-theme.py — one color token per distinct',
    ' * literal hex value used across the app\'s CSS Modules (Layout.module.css\'s',
    ' * always-dark sidebar excluded on purpose). Light values are the original',
    ' * literals (pixel-identical to the pre-dark-mode app); dark values are each',
    ' * color\'s HSL lightness inverted and compressed toward a comfortable range.',
    ' *',
    ' * Not meant to be hand-edited color-by-color — rerun the script after',
    ' * adding new hardcoded colors elsewhere, or hand-add a --c-XXXXXX pair here',
    ' * for a one-off.',
    ' */',
    ':root {',
]
for canon in sorted(tokens):
    var_name, light, _dark = tokens[canon]
    lines.append(f'  {var_name}: {light};')
lines.append('}')
lines.append('')
lines.append('@media (prefers-color-scheme: dark) {')
lines.append('  :root {')
for canon in sorted(tokens):
    var_name, _light, dark = tokens[canon]
    lines.append(f'    {var_name}: {dark};')
lines.append('  }')
lines.append('}')
lines.append('')

theme_path = os.path.join(ROOT, 'theme.css')
with open(theme_path, 'w') as f:
    f.write('\n'.join(lines) + '\n')

print(f'wrote {theme_path} ({len(tokens)} tokens)')
